// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e254ccf7-8cb2-49ce-9dce-1bdf50e5cf70";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSoilMoistureThresholdChange();
void onAutoPumpTriggerChange();
void onManualPumpTriggerChange();

float durationWaterPumpOn;
float humidity;
float temperature;
int lightIntensity;
int soilMoisture;
int soilMoistureThreshold;
bool autoPumpTrigger;
bool manualPumpTrigger;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(durationWaterPumpOn, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lightIntensity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soilMoisture, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(soilMoistureThreshold, READWRITE, ON_CHANGE, onSoilMoistureThresholdChange);
  ArduinoCloud.addProperty(autoPumpTrigger, READWRITE, ON_CHANGE, onAutoPumpTriggerChange);
  ArduinoCloud.addProperty(manualPumpTrigger, READWRITE, ON_CHANGE, onManualPumpTriggerChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
